checkpoint: ???
device: mps
inference_interval: 0.02
sensitivity: 1.0
smoothing:
  click_threshold: 0.4
  scroll_threshold: 0.4
  move_threshold: 0.4
  confidence_threshold: 0.4
  hold_frames: 5

hydra:
  run:
    dir: .
  output_subdir: null
  job:
    chdir: false
