checkpoint: ???
device: mps
inference_interval: 0.02
sensitivity: 1.0
smoothing:
  click_threshold: 0.5
  scroll_threshold: 0.5
  move_threshold: 0.5
  confidence_threshold: 0.5
  hold_frames: 3

hydra:
  run:
    dir: .
  output_subdir: null
  job:
    chdir: false
